// Author: Dustin Pilgrim
// License: GPL-3.0-only
//
// Description: Creates an initial ~/.config/stasis/stasis.rune on first run.
// Chooses a desktop vs laptop template based on chassis detection.

use std::fs;
use std::io;

use crate::core::utils::{ChassisKind, detect_chassis};

pub fn ensure_user_config_exists() -> io::Result<()> {
    let path = super::default_user_config_path();

    // If already present, do nothing.
    if path.exists() {
        return Ok(());
    }

    write_default_config(&path)?;

    eventline::info!("Stasis: created default config at {}", path.display());
    Ok(())
}

pub(crate) fn write_default_config(path: &std::path::Path) -> io::Result<()> {
    if let Some(dir) = path.parent()
        && !dir.exists()
    {
        fs::create_dir_all(dir)?;
    }

    fs::write(path, default_config_contents())
}

pub(crate) fn default_config_contents() -> String {
    match detect_chassis() {
        ChassisKind::Laptop => default_laptop_config(),
        _ => default_desktop_config(), // Desktop + Unknown fall back here
    }
}

fn default_laptop_config() -> String {
    r#"
# This file was auto-generated by Stasis on first run
# Feel free to customize it to your needs
# Master config reference: `/usr/share/doc/stasis/stasis.rune`

@author "Dustin Pilgrim"
@description "Lightweight feature packed idle manager for Wayland"

# Semantics:
# - Everything lives under `default:` (and optional profile blocks).
# - On laptops, Stasis chooses between:
#     `default.ac:` and `default.battery:`
#   depending on current power source.
# - Lid actions live under `default:` (globals) so they apply on BOTH AC and Battery
#   unless a profile overlays/clears them.

default:
  # Optional: listen for login1 sleep/wake state (default false).
  # Lock tracking uses LockedHint automatically, with the locker process as a
  # fallback; this setting does not run or select your locker command.
  #enable_loginctl_integration true

  # Optional: listen for session D-Bus inhibit traffic (default true).
  # This gate is not browser-only: browsers, Steam, and other desktop apps can
  # request inhibit through standard D-Bus/portal paths.
  # Browser/media-tab inhibit lives here, not under monitor_media.
  # Disable this only if you explicitly do not want D-Bus inhibit requests
  # to pause idle progression.
  #enable_dbus_inhibit false

  # Optional: run before suspending (hook).
  #
  # Behavior:
  # - This command runs RIGHT BEFORE the suspend step, and Stasis currently WAITS
  #   for it to exit before continuing to suspend.
  # - Therefore, a foreground screen locker (e.g. `swaylock -F`, `hyprlock`) will
  #   BLOCK suspend unless it daemonizes / returns quickly.
  # - Also: do NOT run your locker BOTH here and in `lock_screen.command`.
  #   If you already have a lock step, leave `pre_suspend_command` unset.
  #
  # Good uses:
  #   pre_suspend_command "sync"
  #   pre_suspend_command "~/.local/bin/my-pre-sleep-hook"
  #
  # If you do NOT have a lock step and you want "lock right before suspend",
  # use a locker that exits immediately (daemon/background), e.g. via a wrapper script.
  #pre_suspend_command "sync"

  # Non-browser media/audio inhibit only. Browser/media-tab inhibit is handled
  # by enable_dbus_inhibit above.
  monitor_media true
  ignore_remote_media true # ignore remote players (spotify/kdeconnect/etc.)

  # Media normally pauses the entire plan. Use "suspend" to allow lock, DPMS,
  # and hardware low-power mode while blocking only automatic suspend.
  media_inhibit_scope "all"

  # Optional: ignore these media sources for media inhibit (case-insensitive)
  #media_blacklist ["spotify"]

  # Media sources that block only automatic suspend while actively playing.
  suspend_inhibit_media [ ]

  # Debounce window in seconds before starting the plan (default 0)
  #debounce_seconds 4

  # Notify when resuming from IPC pause (e.g., `stasis pause 1h`)
  #notify_on_unpause true

  # Global gate: notifications before steps only happen if this is true
  #notify_before_action true

  # Icon name/path for Stasis-generated notifications. Defaults to "stasis".
  # Set to "" to disable the default icon, or override per step.
  #notification_icon "dialog-warning"

  # App/process inhibit patterns (strings or regex literals)
  inhibit_apps [
    "vlc"
    "mpv"
    r"steam_app_.*"
  ]

  # App/process patterns that block only automatic suspend. The remaining
  # suspend timeout resumes after the last matching app exits.
  suspend_inhibit_apps [ ]

  # -----------------------------
  # Prepare sleep command
  # -----------------------------
  # Shell command to run immediately when logind emits PrepareForSleep(true).
  # Unlike `pre_suspend_command`, this triggers when sleep is initiated
  # externally (e.g., closing lid, systemctl suspend), not by stasis idle plan.
  #
  # Examples:
  #   prepare_sleep_command "swaylock -f"
  # -----------------------------
  #prepare_sleep_command ""

  # -----------------------------
  # Hardware low-power mode
  #
  # After the DPMS (display-off) step fires, Stasis can apply conservative
  # power-saving to supported hardware (GPU runtime PM, amdgpu DPM). Everything
  # it changes is snapshotted and restored EXACTLY on any resume path.
  #
  # Requires write access to GPU sysfs power-control files. On most distros you
  # need either elevated privileges or a udev rule, e.g.:
  #   /etc/udev/rules.d/99-stasis-gpu-pm.rules:
  #   SUBSYSTEM=="pci", KERNEL=="0000:01:00.0", ATTR{power/control}="auto"
  # (adjust the PCI address to your GPU; check `lspci -D`)
  #
  # If Stasis can't write a file, it skips it and logs a message.
  # -----------------------------
  #low_power_when_idle false
  #low_power_when_idle_timeout 10

  # -----------------------------
  # Lid actions (LAPTOP ONLY)
  #
  # Shell commands run immediately on lid close or open.
  # Lid close/open also pause/resume the plan timers regardless.
  #
  # These are GLOBAL under `default:` so they apply to BOTH `ac:` and `battery:` plans.
  # A profile can override them or clear them (set to "").
  #
  # Examples:
  #   lid_close_action "swaylock"
  #   lid_open_action  "brightnessctl set 60%"
  # -----------------------------
  #lid_close_action "swaylock"
  #lid_open_action  ""

  # Laptop plan: AC power (relaxed)
  ac:
    brightness:
      timeout 300 # 5 minute(s)
      command "brightnessctl set 50%"
    end

    dpms:
      timeout 120 # 2 minute(s) after brightness
      command "niri msg action power-off-monitors"
      resume_command "niri msg action power-on-monitors"
    end

    lock_screen:
      timeout 180 # 3 minute(s) after dpms
      command "swaylock"

      # Optional per-step notification:
      #notification "Locking session soon"
      #notification_icon "dialog-warning"
      #notify_seconds_before 10
    end

    suspend:
      timeout 600 # 10 minute(s) after lock
      command "systemctl suspend"
    end
  end

  # Laptop plan: Battery power (aggressive)
  battery:
    brightness:
      timeout 60 # 1 minute(s)
      command "brightnessctl set 30%"
    end

    dpms:
      timeout 30 # 30 second(s) after brightness
      command "niri msg action power-off-monitors"
      resume_command "niri msg action power-on-monitors"
    end

    lock_screen:
      timeout 60 # 1 minute(s) after dpms
      command "swaylock"
    end

    suspend:
      timeout 120 # 2 minute(s) after lock
      command "systemctl suspend"
    end
  end
end
"#
    .trim_start()
    .to_string()
}

fn default_desktop_config() -> String {
    r#"
# This file was auto-generated by Stasis on first run
# Feel free to customize it to your needs
# Master config reference: `/usr/share/doc/stasis/stasis.rune`

@author "Dustin Pilgrim"
@description "Lightweight feature packed idle manager for Wayland"

default:
  # Optional: listen for login1 sleep/wake state (default false).
  # Lock tracking uses LockedHint automatically, with the locker process as a
  # fallback; this setting does not run or select your locker command.
  #enable_loginctl_integration true

  # Optional: listen for session D-Bus inhibit traffic (default true).
  # This gate is not browser-only: browsers, Steam, and other desktop apps can
  # request inhibit through standard D-Bus/portal paths.
  # Browser/media-tab inhibit lives here, not under monitor_media.
  # Disable this only if you explicitly do not want D-Bus inhibit requests
  # to pause idle progression.
  #enable_dbus_inhibit false

  # Optional: run before suspending (e.g., ensure lock is up)
  #pre_suspend_command "swaylock"

  # Non-browser media/audio inhibit only. Browser/media-tab inhibit is handled
  # by enable_dbus_inhibit above.
  monitor_media true
  ignore_remote_media true # ignore remote players (spotify/kdeconnect/etc.)

  # Media normally pauses the entire plan. Use "suspend" to allow lock, DPMS,
  # and hardware low-power mode while blocking only automatic suspend.
  media_inhibit_scope "all"

  # Optional: ignore these media sources for media inhibit (case-insensitive)
  #media_blacklist ["spotify"]

  # Media sources that block only automatic suspend while actively playing.
  suspend_inhibit_media [ ]

  # Debounce window in seconds before starting the plan (default 0)
  #debounce_seconds 4

  # Notify when resuming from IPC pause (e.g., `stasis pause 1h`)
  #notify_on_unpause true

  # Global gate: notifications before steps only happen if this is true
  #notify_before_action true

  # Icon name/path for Stasis-generated notifications. Defaults to "stasis".
  # Set to "" to disable the default icon, or override per step.
  #notification_icon "dialog-warning"

  # App/process inhibit patterns (strings or regex literals)
  inhibit_apps [
    "vlc"
    "mpv"
    r"steam_app_.*"
  ]

  # App/process patterns that block only automatic suspend. The remaining
  # suspend timeout resumes after the last matching app exits.
  suspend_inhibit_apps [ ]

  # -----------------------------
  # Hardware low-power mode
  #
  # After the DPMS (display-off) step fires, Stasis can apply conservative
  # power-saving to supported hardware (GPU runtime PM, amdgpu DPM). Everything
  # it changes is snapshotted and restored EXACTLY on any resume path.
  #
  # Requires write access to GPU sysfs power-control files. On most distros you
  # need either elevated privileges or a udev rule, e.g.:
  #   /etc/udev/rules.d/99-stasis-gpu-pm.rules:
  #   SUBSYSTEM=="pci", KERNEL=="0000:01:00.0", ATTR{power/control}="auto"
  # (adjust the PCI address to your GPU; check `lspci -D`)
  #
  # If Stasis can't write a file, it skips it and logs a message.
  # -----------------------------
  #low_power_when_idle false
  #low_power_when_idle_timeout 10

  lock_screen:
    timeout 300 # 5 minute(s)
    command "swaylock"

    # Optional per-step notification:
    #notification "Locking in 10s"
    #notification_icon "dialog-warning"
    #notify_seconds_before 10
  end

  dpms:
    timeout 60 # 1 minute(s) after lock
    command "niri msg action power-off-monitors"
    resume_command "niri msg action power-on-monitors"
  end

  suspend:
    timeout 1800 # 30 minute(s) after dpms
    command "systemctl suspend"
  end
end
"#
    .trim_start()
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use rune_cfg::RuneConfig;

    fn assert_valid_low_power_template(contents: String) {
        assert_eq!(contents.matches("#low_power_when_idle false").count(), 1);
        assert_eq!(
            contents.matches("#low_power_when_idle_timeout 10").count(),
            1
        );
        assert_eq!(contents.matches("media_inhibit_scope \"all\"").count(), 1);
        assert_eq!(contents.matches("suspend_inhibit_apps [ ]").count(), 1);
        assert_eq!(contents.matches("suspend_inhibit_media [ ]").count(), 1);

        let rc = RuneConfig::from_str(&contents).expect("bootstrap config should be valid Rune");
        super::super::parse_config_file(&rc)
            .expect("bootstrap config should satisfy the Stasis schema");
    }

    #[test]
    fn laptop_template_includes_low_power_settings() {
        assert_valid_low_power_template(default_laptop_config());
    }

    #[test]
    fn desktop_template_includes_low_power_settings() {
        assert_valid_low_power_template(default_desktop_config());
    }
}
